// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package dbsql

import (
	"context"

	pgvector "github.com/pgvector/pgvector-go"
)

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO documents (
    source_uri,
    media_type,
    content_type,
    metadata
)
VALUES (
    $1,
    $2,
    $3,
    $4::jsonb
)
ON CONFLICT (source_uri) DO UPDATE
SET media_type = EXCLUDED.media_type,
    content_type = EXCLUDED.content_type,
    metadata = EXCLUDED.metadata,
    updated_at = CURRENT_TIMESTAMP
RETURNING id
`

type UpsertDocumentParams struct {
	SourceUri   string
	MediaType   string
	ContentType string
	Metadata    []byte
}

// UpsertDocument
//
//	INSERT INTO documents (
//	    source_uri,
//	    media_type,
//	    content_type,
//	    metadata
//	)
//	VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4::jsonb
//	)
//	ON CONFLICT (source_uri) DO UPDATE
//	SET media_type = EXCLUDED.media_type,
//	    content_type = EXCLUDED.content_type,
//	    metadata = EXCLUDED.metadata,
//	    updated_at = CURRENT_TIMESTAMP
//	RETURNING id
func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertDocument,
		arg.SourceUri,
		arg.MediaType,
		arg.ContentType,
		arg.Metadata,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertEmbedding = `-- name: UpsertEmbedding :exec
INSERT INTO embeddings (
    document_id,
    model,
    segment_index,
    start_ms,
    end_ms,
    embedding,
    metadata
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6::vector,
    $7::jsonb
)
ON CONFLICT (document_id, model, segment_index) DO UPDATE
SET start_ms = EXCLUDED.start_ms,
    end_ms = EXCLUDED.end_ms,
    embedding = EXCLUDED.embedding,
    metadata = EXCLUDED.metadata,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertEmbeddingParams struct {
	DocumentID   int64
	Model        string
	SegmentIndex int32
	StartMs      *int64
	EndMs        *int64
	Embedding    pgvector.Vector
	Metadata     []byte
}

// UpsertEmbedding
//
//	INSERT INTO embeddings (
//	    document_id,
//	    model,
//	    segment_index,
//	    start_ms,
//	    end_ms,
//	    embedding,
//	    metadata
//	)
//	VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6::vector,
//	    $7::jsonb
//	)
//	ON CONFLICT (document_id, model, segment_index) DO UPDATE
//	SET start_ms = EXCLUDED.start_ms,
//	    end_ms = EXCLUDED.end_ms,
//	    embedding = EXCLUDED.embedding,
//	    metadata = EXCLUDED.metadata,
//	    updated_at = CURRENT_TIMESTAMP
func (q *Queries) UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) error {
	_, err := q.db.Exec(ctx, upsertEmbedding,
		arg.DocumentID,
		arg.Model,
		arg.SegmentIndex,
		arg.StartMs,
		arg.EndMs,
		arg.Embedding,
		arg.Metadata,
	)
	return err
}
