// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingestion_jobs.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimIngestionJob = `-- name: ClaimIngestionJob :one
WITH candidate AS (
    SELECT id
    FROM ingestion_jobs
    WHERE status = 'pending'
      AND available_at <= CURRENT_TIMESTAMP
    ORDER BY available_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE ingestion_jobs AS job
SET status = 'processing',
    attempts = job.attempts + 1,
    started_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
FROM candidate
WHERE job.id = candidate.id
  AND job.status = 'pending'
RETURNING job.id, job.bucket, job.object_key, job.object_version, job.etag, job.size_bytes, job.content_type, job.status, job.attempts, job.last_error, job.available_at, job.started_at, job.completed_at, job.created_at, job.updated_at
`

// ClaimIngestionJob
//
//	WITH candidate AS (
//	    SELECT id
//	    FROM ingestion_jobs
//	    WHERE status = 'pending'
//	      AND available_at <= CURRENT_TIMESTAMP
//	    ORDER BY available_at, id
//	    FOR UPDATE SKIP LOCKED
//	    LIMIT 1
//	)
//	UPDATE ingestion_jobs AS job
//	SET status = 'processing',
//	    attempts = job.attempts + 1,
//	    started_at = CURRENT_TIMESTAMP,
//	    updated_at = CURRENT_TIMESTAMP
//	FROM candidate
//	WHERE job.id = candidate.id
//	  AND job.status = 'pending'
//	RETURNING job.id, job.bucket, job.object_key, job.object_version, job.etag, job.size_bytes, job.content_type, job.status, job.attempts, job.last_error, job.available_at, job.started_at, job.completed_at, job.created_at, job.updated_at
func (q *Queries) ClaimIngestionJob(ctx context.Context) (IngestionJob, error) {
	row := q.db.QueryRow(ctx, claimIngestionJob)
	var i IngestionJob
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.ObjectKey,
		&i.ObjectVersion,
		&i.Etag,
		&i.SizeBytes,
		&i.ContentType,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.AvailableAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeIngestionJob = `-- name: CompleteIngestionJob :one
UPDATE ingestion_jobs
SET status = $1,
    last_error = $2,
    completed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
  AND status = 'processing'
RETURNING id
`

type CompleteIngestionJobParams struct {
	TerminalStatus string
	Reason         string
	ID             int64
}

// CompleteIngestionJob
//
//	UPDATE ingestion_jobs
//	SET status = $1,
//	    last_error = $2,
//	    completed_at = CURRENT_TIMESTAMP,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $3
//	  AND status = 'processing'
//	RETURNING id
func (q *Queries) CompleteIngestionJob(ctx context.Context, arg CompleteIngestionJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, completeIngestionJob, arg.TerminalStatus, arg.Reason, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const enqueueIngestionJob = `-- name: EnqueueIngestionJob :one
WITH inserted AS (
    INSERT INTO ingestion_jobs (
        bucket,
        object_key,
        object_version,
        etag,
        size_bytes,
        content_type
    )
    VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    )
    ON CONFLICT (bucket, object_key, object_version, etag) DO NOTHING
    RETURNING id
)
SELECT EXISTS (SELECT 1 FROM inserted) AS inserted
`

type EnqueueIngestionJobParams struct {
	Bucket        string
	ObjectKey     string
	ObjectVersion string
	Etag          string
	SizeBytes     *int64
	ContentType   string
}

// EnqueueIngestionJob
//
//	WITH inserted AS (
//	    INSERT INTO ingestion_jobs (
//	        bucket,
//	        object_key,
//	        object_version,
//	        etag,
//	        size_bytes,
//	        content_type
//	    )
//	    VALUES (
//	        $1,
//	        $2,
//	        $3,
//	        $4,
//	        $5,
//	        $6
//	    )
//	    ON CONFLICT (bucket, object_key, object_version, etag) DO NOTHING
//	    RETURNING id
//	)
//	SELECT EXISTS (SELECT 1 FROM inserted) AS inserted
func (q *Queries) EnqueueIngestionJob(ctx context.Context, arg EnqueueIngestionJobParams) (bool, error) {
	row := q.db.QueryRow(ctx, enqueueIngestionJob,
		arg.Bucket,
		arg.ObjectKey,
		arg.ObjectVersion,
		arg.Etag,
		arg.SizeBytes,
		arg.ContentType,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const requeueFailedIngestionJob = `-- name: RequeueFailedIngestionJob :one
UPDATE ingestion_jobs
SET status = 'pending',
    attempts = 0,
    last_error = '',
    available_at = CURRENT_TIMESTAMP,
    started_at = NULL,
    completed_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND status = 'failed'
RETURNING id
`

// RequeueFailedIngestionJob
//
//	UPDATE ingestion_jobs
//	SET status = 'pending',
//	    attempts = 0,
//	    last_error = '',
//	    available_at = CURRENT_TIMESTAMP,
//	    started_at = NULL,
//	    completed_at = NULL,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1
//	  AND status = 'failed'
//	RETURNING id
func (q *Queries) RequeueFailedIngestionJob(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, requeueFailedIngestionJob, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const retryIngestionJob = `-- name: RetryIngestionJob :one
UPDATE ingestion_jobs
SET status = 'pending',
    available_at = $1,
    last_error = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
  AND status = 'processing'
RETURNING id
`

type RetryIngestionJobParams struct {
	AvailableAt pgtype.Timestamptz
	Reason      string
	ID          int64
}

// RetryIngestionJob
//
//	UPDATE ingestion_jobs
//	SET status = 'pending',
//	    available_at = $1,
//	    last_error = $2,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $3
//	  AND status = 'processing'
//	RETURNING id
func (q *Queries) RetryIngestionJob(ctx context.Context, arg RetryIngestionJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, retryIngestionJob, arg.AvailableAt, arg.Reason, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
