// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingestion_jobs.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimIngestionJob = `-- name: ClaimIngestionJob :one
WITH candidate AS (
    SELECT id
    FROM ingestion_jobs
    WHERE (status = 'pending' AND available_at <= CURRENT_TIMESTAMP)
       OR (status = 'processing' AND lease_expires_at <= CURRENT_TIMESTAMP)
    ORDER BY CASE WHEN status = 'pending' THEN available_at ELSE lease_expires_at END, id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE ingestion_jobs AS job
SET status = 'processing',
    attempts = job.attempts + 1,
    started_at = CURRENT_TIMESTAMP,
    lease_token = $1,
    lease_expires_at = CURRENT_TIMESTAMP + ($2::BIGINT * INTERVAL '1 millisecond'),
    heartbeat_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
FROM candidate
WHERE job.id = candidate.id
  AND (
      (job.status = 'pending' AND job.available_at <= CURRENT_TIMESTAMP)
      OR (job.status = 'processing' AND job.lease_expires_at <= CURRENT_TIMESTAMP)
  )
RETURNING job.id, job.bucket, job.object_key, job.object_version, job.etag, job.size_bytes, job.content_type, job.status, job.attempts, job.last_error, job.available_at, job.started_at, job.completed_at, job.created_at, job.updated_at, job.lease_token, job.lease_expires_at, job.heartbeat_at
`

type ClaimIngestionJobParams struct {
	LeaseToken                string
	LeaseDurationMilliseconds int64
}

// ClaimIngestionJob
//
//	WITH candidate AS (
//	    SELECT id
//	    FROM ingestion_jobs
//	    WHERE (status = 'pending' AND available_at <= CURRENT_TIMESTAMP)
//	       OR (status = 'processing' AND lease_expires_at <= CURRENT_TIMESTAMP)
//	    ORDER BY CASE WHEN status = 'pending' THEN available_at ELSE lease_expires_at END, id
//	    FOR UPDATE SKIP LOCKED
//	    LIMIT 1
//	)
//	UPDATE ingestion_jobs AS job
//	SET status = 'processing',
//	    attempts = job.attempts + 1,
//	    started_at = CURRENT_TIMESTAMP,
//	    lease_token = $1,
//	    lease_expires_at = CURRENT_TIMESTAMP + ($2::BIGINT * INTERVAL '1 millisecond'),
//	    heartbeat_at = CURRENT_TIMESTAMP,
//	    updated_at = CURRENT_TIMESTAMP
//	FROM candidate
//	WHERE job.id = candidate.id
//	  AND (
//	      (job.status = 'pending' AND job.available_at <= CURRENT_TIMESTAMP)
//	      OR (job.status = 'processing' AND job.lease_expires_at <= CURRENT_TIMESTAMP)
//	  )
//	RETURNING job.id, job.bucket, job.object_key, job.object_version, job.etag, job.size_bytes, job.content_type, job.status, job.attempts, job.last_error, job.available_at, job.started_at, job.completed_at, job.created_at, job.updated_at, job.lease_token, job.lease_expires_at, job.heartbeat_at
func (q *Queries) ClaimIngestionJob(ctx context.Context, arg ClaimIngestionJobParams) (IngestionJob, error) {
	row := q.db.QueryRow(ctx, claimIngestionJob, arg.LeaseToken, arg.LeaseDurationMilliseconds)
	var i IngestionJob
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.ObjectKey,
		&i.ObjectVersion,
		&i.Etag,
		&i.SizeBytes,
		&i.ContentType,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.AvailableAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const completeIngestionJob = `-- name: CompleteIngestionJob :one
UPDATE ingestion_jobs
SET status = $1,
    last_error = $2,
    completed_at = CURRENT_TIMESTAMP,
    lease_token = '',
    lease_expires_at = NULL,
    heartbeat_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
  AND status = 'processing'
  AND lease_token = $4
  AND lease_expires_at > CURRENT_TIMESTAMP
RETURNING id
`

type CompleteIngestionJobParams struct {
	TerminalStatus string
	Reason         string
	ID             int64
	LeaseToken     string
}

// CompleteIngestionJob
//
//	UPDATE ingestion_jobs
//	SET status = $1,
//	    last_error = $2,
//	    completed_at = CURRENT_TIMESTAMP,
//	    lease_token = '',
//	    lease_expires_at = NULL,
//	    heartbeat_at = NULL,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $3
//	  AND status = 'processing'
//	  AND lease_token = $4
//	  AND lease_expires_at > CURRENT_TIMESTAMP
//	RETURNING id
func (q *Queries) CompleteIngestionJob(ctx context.Context, arg CompleteIngestionJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, completeIngestionJob,
		arg.TerminalStatus,
		arg.Reason,
		arg.ID,
		arg.LeaseToken,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const enqueueIngestionJob = `-- name: EnqueueIngestionJob :one
WITH inserted AS (
    INSERT INTO ingestion_jobs (
        bucket,
        object_key,
        object_version,
        etag,
        size_bytes,
        content_type
    )
    VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    )
    ON CONFLICT (bucket, object_key, object_version, etag) DO NOTHING
    RETURNING id
)
SELECT EXISTS (SELECT 1 FROM inserted) AS inserted
`

type EnqueueIngestionJobParams struct {
	Bucket        string
	ObjectKey     string
	ObjectVersion string
	Etag          string
	SizeBytes     *int64
	ContentType   string
}

// EnqueueIngestionJob
//
//	WITH inserted AS (
//	    INSERT INTO ingestion_jobs (
//	        bucket,
//	        object_key,
//	        object_version,
//	        etag,
//	        size_bytes,
//	        content_type
//	    )
//	    VALUES (
//	        $1,
//	        $2,
//	        $3,
//	        $4,
//	        $5,
//	        $6
//	    )
//	    ON CONFLICT (bucket, object_key, object_version, etag) DO NOTHING
//	    RETURNING id
//	)
//	SELECT EXISTS (SELECT 1 FROM inserted) AS inserted
func (q *Queries) EnqueueIngestionJob(ctx context.Context, arg EnqueueIngestionJobParams) (bool, error) {
	row := q.db.QueryRow(ctx, enqueueIngestionJob,
		arg.Bucket,
		arg.ObjectKey,
		arg.ObjectVersion,
		arg.Etag,
		arg.SizeBytes,
		arg.ContentType,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const heartbeatIngestionJob = `-- name: HeartbeatIngestionJob :one
UPDATE ingestion_jobs
SET lease_expires_at = CURRENT_TIMESTAMP + ($1::BIGINT * INTERVAL '1 millisecond'),
    heartbeat_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
  AND status = 'processing'
  AND lease_token = $3
  AND lease_expires_at > CURRENT_TIMESTAMP
RETURNING id
`

type HeartbeatIngestionJobParams struct {
	LeaseDurationMilliseconds int64
	ID                        int64
	LeaseToken                string
}

// HeartbeatIngestionJob
//
//	UPDATE ingestion_jobs
//	SET lease_expires_at = CURRENT_TIMESTAMP + ($1::BIGINT * INTERVAL '1 millisecond'),
//	    heartbeat_at = CURRENT_TIMESTAMP,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $2
//	  AND status = 'processing'
//	  AND lease_token = $3
//	  AND lease_expires_at > CURRENT_TIMESTAMP
//	RETURNING id
func (q *Queries) HeartbeatIngestionJob(ctx context.Context, arg HeartbeatIngestionJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, heartbeatIngestionJob, arg.LeaseDurationMilliseconds, arg.ID, arg.LeaseToken)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const requeueFailedIngestionJob = `-- name: RequeueFailedIngestionJob :one
UPDATE ingestion_jobs
SET status = 'pending',
    attempts = 0,
    last_error = '',
    available_at = CURRENT_TIMESTAMP,
    started_at = NULL,
    completed_at = NULL,
    lease_token = '',
    lease_expires_at = NULL,
    heartbeat_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND status = 'failed'
RETURNING id
`

// RequeueFailedIngestionJob
//
//	UPDATE ingestion_jobs
//	SET status = 'pending',
//	    attempts = 0,
//	    last_error = '',
//	    available_at = CURRENT_TIMESTAMP,
//	    started_at = NULL,
//	    completed_at = NULL,
//	    lease_token = '',
//	    lease_expires_at = NULL,
//	    heartbeat_at = NULL,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1
//	  AND status = 'failed'
//	RETURNING id
func (q *Queries) RequeueFailedIngestionJob(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, requeueFailedIngestionJob, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const retryIngestionJob = `-- name: RetryIngestionJob :one
UPDATE ingestion_jobs
SET status = 'pending',
    available_at = $1,
    last_error = $2,
    lease_token = '',
    lease_expires_at = NULL,
    heartbeat_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
  AND status = 'processing'
  AND lease_token = $4
  AND lease_expires_at > CURRENT_TIMESTAMP
RETURNING id
`

type RetryIngestionJobParams struct {
	AvailableAt pgtype.Timestamptz
	Reason      string
	ID          int64
	LeaseToken  string
}

// RetryIngestionJob
//
//	UPDATE ingestion_jobs
//	SET status = 'pending',
//	    available_at = $1,
//	    last_error = $2,
//	    lease_token = '',
//	    lease_expires_at = NULL,
//	    heartbeat_at = NULL,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $3
//	  AND status = 'processing'
//	  AND lease_token = $4
//	  AND lease_expires_at > CURRENT_TIMESTAMP
//	RETURNING id
func (q *Queries) RetryIngestionJob(ctx context.Context, arg RetryIngestionJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, retryIngestionJob,
		arg.AvailableAt,
		arg.Reason,
		arg.ID,
		arg.LeaseToken,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
