// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsql

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

type Document struct {
	ID          int64
	SourceUri   string
	MediaType   string
	ContentType string
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Embedding struct {
	ID           int64
	DocumentID   int64
	Model        string
	SegmentIndex int32
	StartMs      *int64
	EndMs        *int64
	Embedding    pgvector.Vector
	Metadata     []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type IngestionJob struct {
	ID             int64
	Bucket         string
	ObjectKey      string
	ObjectVersion  string
	Etag           string
	SizeBytes      *int64
	ContentType    string
	Status         string
	Attempts       int32
	LastError      string
	AvailableAt    pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LeaseToken     string
	LeaseExpiresAt pgtype.Timestamptz
	HeartbeatAt    pgtype.Timestamptz
}
