// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package dbsql

import (
	"context"

	pgvector "github.com/pgvector/pgvector-go"
)

const searchDocuments = `-- name: SearchDocuments :many
SELECT
    d.id AS document_id,
    d.source_uri,
    d.media_type,
    d.content_type,
    d.metadata AS document_metadata,
    e.id AS embedding_id,
    e.segment_index,
    e.start_ms,
    e.end_ms,
    e.metadata AS embedding_metadata,
    (e.embedding <=> $1::vector)::double precision AS distance,
    (1 - (e.embedding <=> $1::vector))::double precision AS similarity
FROM embeddings AS e
JOIN documents AS d ON d.id = e.document_id
WHERE e.model = $2
ORDER BY e.embedding <=> $1::vector, e.id
LIMIT $3::integer
`

type SearchDocumentsParams struct {
	QueryEmbedding pgvector.Vector
	Model          string
	ResultLimit    int32
}

type SearchDocumentsRow struct {
	DocumentID        int64
	SourceUri         string
	MediaType         string
	ContentType       string
	DocumentMetadata  []byte
	EmbeddingID       int64
	SegmentIndex      int32
	StartMs           *int64
	EndMs             *int64
	EmbeddingMetadata []byte
	Distance          float64
	Similarity        float64
}

// SearchDocuments
//
//	SELECT
//	    d.id AS document_id,
//	    d.source_uri,
//	    d.media_type,
//	    d.content_type,
//	    d.metadata AS document_metadata,
//	    e.id AS embedding_id,
//	    e.segment_index,
//	    e.start_ms,
//	    e.end_ms,
//	    e.metadata AS embedding_metadata,
//	    (e.embedding <=> $1::vector)::double precision AS distance,
//	    (1 - (e.embedding <=> $1::vector))::double precision AS similarity
//	FROM embeddings AS e
//	JOIN documents AS d ON d.id = e.document_id
//	WHERE e.model = $2
//	ORDER BY e.embedding <=> $1::vector, e.id
//	LIMIT $3::integer
func (q *Queries) SearchDocuments(ctx context.Context, arg SearchDocumentsParams) ([]SearchDocumentsRow, error) {
	rows, err := q.db.Query(ctx, searchDocuments, arg.QueryEmbedding, arg.Model, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocumentsRow{}
	for rows.Next() {
		var i SearchDocumentsRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.SourceUri,
			&i.MediaType,
			&i.ContentType,
			&i.DocumentMetadata,
			&i.EmbeddingID,
			&i.SegmentIndex,
			&i.StartMs,
			&i.EndMs,
			&i.EmbeddingMetadata,
			&i.Distance,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocumentsByMediaType = `-- name: SearchDocumentsByMediaType :many
SELECT
    d.id AS document_id,
    d.source_uri,
    d.media_type,
    d.content_type,
    d.metadata AS document_metadata,
    e.id AS embedding_id,
    e.segment_index,
    e.start_ms,
    e.end_ms,
    e.metadata AS embedding_metadata,
    (e.embedding <=> $1::vector)::double precision AS distance,
    (1 - (e.embedding <=> $1::vector))::double precision AS similarity
FROM embeddings AS e
JOIN documents AS d ON d.id = e.document_id
WHERE e.model = $2
  AND d.media_type = $3
ORDER BY e.embedding <=> $1::vector, e.id
LIMIT $4::integer
`

type SearchDocumentsByMediaTypeParams struct {
	QueryEmbedding pgvector.Vector
	Model          string
	MediaType      string
	ResultLimit    int32
}

type SearchDocumentsByMediaTypeRow struct {
	DocumentID        int64
	SourceUri         string
	MediaType         string
	ContentType       string
	DocumentMetadata  []byte
	EmbeddingID       int64
	SegmentIndex      int32
	StartMs           *int64
	EndMs             *int64
	EmbeddingMetadata []byte
	Distance          float64
	Similarity        float64
}

// SearchDocumentsByMediaType
//
//	SELECT
//	    d.id AS document_id,
//	    d.source_uri,
//	    d.media_type,
//	    d.content_type,
//	    d.metadata AS document_metadata,
//	    e.id AS embedding_id,
//	    e.segment_index,
//	    e.start_ms,
//	    e.end_ms,
//	    e.metadata AS embedding_metadata,
//	    (e.embedding <=> $1::vector)::double precision AS distance,
//	    (1 - (e.embedding <=> $1::vector))::double precision AS similarity
//	FROM embeddings AS e
//	JOIN documents AS d ON d.id = e.document_id
//	WHERE e.model = $2
//	  AND d.media_type = $3
//	ORDER BY e.embedding <=> $1::vector, e.id
//	LIMIT $4::integer
func (q *Queries) SearchDocumentsByMediaType(ctx context.Context, arg SearchDocumentsByMediaTypeParams) ([]SearchDocumentsByMediaTypeRow, error) {
	rows, err := q.db.Query(ctx, searchDocumentsByMediaType,
		arg.QueryEmbedding,
		arg.Model,
		arg.MediaType,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocumentsByMediaTypeRow{}
	for rows.Next() {
		var i SearchDocumentsByMediaTypeRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.SourceUri,
			&i.MediaType,
			&i.ContentType,
			&i.DocumentMetadata,
			&i.EmbeddingID,
			&i.SegmentIndex,
			&i.StartMs,
			&i.EndMs,
			&i.EmbeddingMetadata,
			&i.Distance,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
